# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy acr cicd

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Load .env variables into environment
      uses: falti/dotenv-action@v1.1.4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
  deploy_identity_img:
    name: Deploy Identity Image
    needs: [build] 
    uses: ./.github/workflows/deploy-acr-template.yaml
    with:
      image-name: identity
      dockerfile-path: Docker/identity-build
    secrets:
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  deploy_order_img:
    name: Deploy Order Image
    needs: [build] 
    uses: ./.github/workflows/deploy-acr-template.yaml
    with:
      image-name: order
      dockerfile-path: Docker/order-build
    secrets:
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  deploy_common_functions_img:
    name: Deploy Common Functions Image
    needs: [build] 
    uses: ./.github/workflows/deploy-acr-template.yaml
    with:
      image-name: common_functions
      dockerfile-path: Docker/commonfunctions-build
    secrets:
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}