# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Identity services cicd

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "Common/**"
      - "Microservices/Identity/**"
      - ".github/workflows/identity-ci.yaml"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Microservices/Identity/Identity.API
    - name: Build
      run: dotnet build Microservices/Identity/Identity.API --no-restore
    - name: Test
      run: dotnet test Microservices/Identity/Identity.API --no-build --verbosity normal