# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Identity services cicd

on:
  push:
    branches: [ "main" ]
    paths:
      - "Common/**"
      - "Microservices/Identity/**"
      - ".github/workflows/identity-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "Common/**"
      - "Microservices/Identity/**"
      - ".github/workflows/identity-ci.yaml"
  workflow_dispatch:
    
env:
  AZURE_CONTAINER_REGISTRY: acr_name
  CONTAINER_APP_NAME: ca_name
  RESOURCE_GROUP: rg_name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Echo something
      run: echo 'haha'