# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Inventory services cicd

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "Common/**"
      - "Microservices/Inventory/**"
      - ".github/workflows/inventory-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Microservices/Inventory/Inventory.API
    - name: Build
      run: dotnet build Microservices/Inventory/Inventory.API --no-restore
    - name: Test
      run: dotnet test Microservices/Inventory/Inventory.API --no-build --verbosity normal
