# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Identity services cicd

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: demoazurethiendo
  IDENTITY_CONTAINER_APP_NAME: identity
  ORDER_CONTAINER_APP_NAME: order
  COMMONFUNTIONS_CONTAINER_APP_NAME: commonfunctions
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Load .env variables into environment
      uses: falti/dotenv-action@v1.1.4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Identity image to ACR
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IDENTITY_CONTAINER_APP_NAME }}:${{ github.sha }}
        file: Devops/identity-build
    
    - name: Build and push Order image to ACR
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.ORDER_CONTAINER_APP_NAME }}:${{ github.sha }}
        file: Devops/order-build
    
    - name: Build and push Common functions image to ACR
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.COMMONFUNTIONS_CONTAINER_APP_NAME }}:${{ github.sha }}
        file: Devops/commonfunctions-build